### ISSUE TITLE
Usen leGanaA

### ISSUE THREAD

**Issue by josibuttazzoni** [martinamattioli/TPLogico#5]
En` partidoGanadorEnLaProvincia(Partido,Provincia)`, por lo que entiendo, el consecuente del forall deberia ser `leGanaA `porque eso es lo que hace que gane en la provincia

**Comment by martinamattioli** [comment]
Lo habiamos pensado pero leGanaA tiene como individuos a los candidatos, no a los partidos

**Comment by josibuttazzoni** [comment]
Claro, es que en realidad la idea era que el que tenia que ganar en todas las provincias era el candidato, no el partido. Pero sabemos que estaba medio confuso, asi que si queda asi no esta mal tampoco

**Comment by Matiduraan** [comment]
Ok, lo dejamos asi entonces?
